version: '2'

services:
    app:
      restart: always
      expose:
        - "5000"
      build:
        context: ../
        dockerfile: ops/Dockerfile
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=example
        - POSTGRES_ADDRESS=postgres:5432   
      command: bash -c "cd flask && gunicorn -b :5000 app:app --timeout 15 --keep-alive 5"
    
    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      links:
        - "postgres:postgres"
        - "app:app"

    data:
      restart: always
      image: postgres:latest
      volumes:
        - /var/lib/postgresql
      command: "true"

    postgres:
      restart: always
      image: postgres:latest
      environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=example
      volumes_from:
        - data
      ports:
        - "5432:5432"