version: '2'

services:
    app:
      restart: always
      expose:
        - "5000"
      build:
        context: ../
        dockerfile: ops/Dockerfile
      command: bash -c "cd flask && gunicorn -b :5000 app:app --timeout 15 --keep-alive 5"
    
    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      links:
        - "app:app"  